name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8.0.352+8
        distribution: temurin
        cache: 'gradle'
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      id: build
      run: ./gradlew build --no-daemon
    
    - name: Get commit ID
      if: steps.build.outputs.status == 'failure'
      run: echo ::set-env name=COMMIT_ID::$(git rev-parse HEAD)

    - name: Request JitPack build
      run: curl -X POST https://jitpack.io/com/github/Nopock/Store/COMMIT_ID/build
      env:
        COMMIT_ID: ${{ env.COMMIT_ID }}