name: CI

on:
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8.0.352+8
        distribution: temurin
        cache: 'gradle'
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      id: build
      run: ./gradlew build --no-daemon

    - name: Create Github Release
      if: "contains(github.event.head_commit.message, '--release') && contains(github.ref, 'main')"
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: "This is an automatic release via `Github Actions`. There will be updated patch notes shortly..."
        tag_name: ${{ secrets.RELEASE_VERSION}}
        release_name: Release ${{ secrets.RELEASE_VERSION }}
        draft: false
        prerelease: false
    
    - name: Upload Jar to Github
      if: "contains(github.event.head_commit.message, '--release') && contains(github.ref, 'main')"
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /home/runner/work/Store/Store/build/libs/Store-1.0.jar
        asset_name: Store.jar
        asset_content_type: application/jar