name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8.0.352+8
        distribution: temurin
        cache: 'gradle'
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      id: build
      run: ./gradlew build --no-daemon
    
    - name: Get commit ID
      if: steps.build.outputs.status != 'failure'
      id: commit
      uses: pr-mpt/actions-commit-hash@v2
      with:
        commit: "${{ github.event.workflow_run.head_sha }}"
        prefix: "sha-"

    - name: Request JitPack build
      if: steps.build.outputs.status != 'failure'
      uses: pr-mpt/actions-commit-hash@v2
      env:
        COMMIT_ID: ${{ env.SHORT_SHA }}
      run: curl -s 30 -X POST https://jitpack.io/com/github/Nopock/Store/${{ steps.commit.outputs.short }}/build