name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8.0.352+8
        distribution: temurin
        cache: 'gradle'
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      id: build
      run: ./gradlew build --no-daemon
    
    - name: Get commit ID
      if: steps.build.outputs.status != 'failure'
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Request JitPack build
      if: steps.build.outputs.status != 'failure'
      run: curl -X POST https://jitpack.io/com/github/Nopock/Store/${SHORT_SHA}/build
      env:
        COMMIT_ID: ${{ env.SHORT_SHA }}