name: JitPack Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0.352+8
          distribution: temurin

      - name: Get commit ID
        run: echo ::set-env name=COMMIT_ID::$(git rev-parse HEAD)

      - name: Request JitPack build
        run: curl -X POST https://jitpack.io/com/github/USERNAME/REPO_NAME/COMMIT_ID/build
        env:
          COMMIT_ID: ${{ env.COMMIT_ID }}